### PR TITLE
fix: Data race in CopyPassThru

### LINKED ISSUE #39: Check the CopyPassThru code for race conditions
Issue #37 reported a race condition between setting the pipe and running a command which resulted in an unexpected error, a solution was proposed in pull request #38. 

As this function contains some other goroutines, it might be worthwhile to ensure that no other race conditions are possible.

### PR DESCRIPTION
**Pull request by mafredri**
The fix in #38 was incomplete as it only moved StdoutPipe outside the
goroutine, this commit also moves StdinPipe outside the goroutine so
there is no race when doing Run on the session.

Fixes #39
Related to #38

### CODE REVIEW

File: client.go [hunk 1]
```diff
@@ -157,12 +162,6 @@ func (a *Client) CopyPassThru(ctx context.Context, r io.Reader, remotePath strin
 
 	go func() {
 		defer wg.Done()
-		w, err := a.Session.StdinPipe()
```
Comment (mafredri) [inline client.go:160]: This issue is easy to reproduce by adding a `time.Sleep(time.Second)` above.

**Comment by deansheather** [comment]
@bramvdbogaerde

**Comment by bramvdbogaerde** [comment]
Merged! Thank you for your contribution.
